site_name: EAM-docs
site_description: 2023 Spring 软工项目：企业资产管理系统的说明文档 by Pipeline:passed
site_author: 李飞翰 黄宇翔 李轶凡 张凯文 孙维泽
site_url: https://Kevin-thu.github.io/EAM-docs/

theme:
  name: material
  features:
  # - announce.dismiss
  - content.code.annotate
  # - content.tabs.link
  - content.tooltips
  # - header.autohide
  # - navigation.expand
  - navigation.indexes
  # - navigation.instant
  # - navigation.prune
  - navigation.sections
  - navigation.tabs
  # - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  # - toc.integrate

nav:
  - 项目概述: index.md
  - 需求分析:
    - 用户故事: user/user.md
    - 需求清单: user/list.md
    - 用户用例与流程图: user/table.md
    - 用户权限: user/previlege.md
  - 数据库设计: 
    - 数据库表单: database/database.md
    - ER图: database/er.md
  - 模块设计: 
    - 前端: module/frontend.md
    - 后端: module/backend.md
  - API 设计: api/api.md

copyright: Copyright &copy; Pipeline:passed 2023
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format